// <auto-generated />
using System;
using Infra.Repositories.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Chairs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0716b31-2866-492d-9cfa-efb97fdfc053"),
                            Chairs = 50,
                            Name = "Sala 1"
                        },
                        new
                        {
                            Id = new Guid("49c8c7b2-c769-4103-bbab-977f6521887d"),
                            Chairs = 50,
                            Name = "Sala 2"
                        },
                        new
                        {
                            Id = new Guid("f1dea0ef-40ea-422b-9d8b-9c59d3d55ab9"),
                            Chairs = 50,
                            Name = "Sala 3"
                        },
                        new
                        {
                            Id = new Guid("39ced579-5270-4b0d-a5c4-3004adccc95b"),
                            Chairs = 50,
                            Name = "Sala 4"
                        },
                        new
                        {
                            Id = new Guid("1734970d-f700-4087-91dd-3c67d434cbcf"),
                            Chairs = 50,
                            Name = "Sala 5"
                        },
                        new
                        {
                            Id = new Guid("2e0729ab-ff22-45c4-892f-98ee134a337b"),
                            Chairs = 50,
                            Name = "Sala 6"
                        },
                        new
                        {
                            Id = new Guid("da0509ee-be35-4474-bbc5-6e12c3db97a6"),
                            Chairs = 50,
                            Name = "Sala 7"
                        },
                        new
                        {
                            Id = new Guid("eb5ef3bf-f2d6-4e3f-ae0d-70cbc03dc8bb"),
                            Chairs = 50,
                            Name = "Sala 8"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Animation");

                    b.Property<int>("Audio");

                    b.Property<Guid>("MovieId");

                    b.Property<Guid>("RoomId");

                    b.Property<DateTime>("SessionEnd");

                    b.Property<DateTime>("SessionStart");

                    b.Property<decimal>("TicketValue");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
